#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

chown -R dokku:dokku $(find $PLUGIN_AVAILABLE_PATH/* -maxdepth 0 -type d)
chmod -R 755 $(find $PLUGIN_AVAILABLE_PATH/* -maxdepth 0 -type d)

DOKKU_SERVICES_PATH="$DOKKU_LIB_ROOT/services"

mkdir -p $DOKKU_SERVICES_PATH
chown -R dokku:dokku $(find $DOKKU_SERVICES_PATH -maxdepth 0 -type d)
chmod -R 755 $(find $DOKKU_SERVICES_PATH -maxdepth 0 -type d)
